### ISSUE TITLE
Extend MoveBlock Execute

### ISSUE THREAD

**Issue by Jackcunningolf** [cs481-ekh/s23-scuttlers#216]
- [x] given that execute is called on a moveblock, when figuring out where to move to, a shortest path algorithm will be used to find the shortest path on the map between the current ant and some coordinate
- [x] given that a shortest path has been found, when changing the ant coordinates, then the ant will follow the path til it reaches the destination
- [x] given that the ant is travelling to the new coords, when rendering the map, the ant will be rerendered for every coordinate it passes though the map at an appropriate speed
- [x] given that execute is called on a moveblock, when figuring out where to move to, a shortest path algorithm will be used to find the shortest path on the map between the current ant and some levelObject

Epic: #36

**Comment by Jackcunningolf** [comment]
A shortest path is found between the current ant's coords and a hardcoded value. Will be dynamic once we know for sure that is the correct path, and we confirm that with the ant moving along the shortest path.

{t:180}

**Comment by Jackcunningolf** [comment]
The ant is being rerender and is moving on the map. However, it is too fast and need to figure out how to render at a slower pace.

{t:180}

**Comment by Jackcunningolf** [comment]
ants are now moving at their own speed. Simple movement AIs are working to ants and random movement, but need to make sure that we are not clipping through anything.

{t:240}

**Comment by anthonyoffire** [comment]
Helped out with dynamically finding targets and feeding them to Jack's shortest path setup. Found and fixed the clipping bug, which had to do with ant tile position calculation; if an ant was moving left into a tile, as soon as the ant had 1 pixel in that tile it would be considered to be there. I think it's working completely now.
{t:300}

**Comment by anthonyoffire** [comment]
Bug fixes
{t:60}

**Comment by anthonyoffire** [comment]
task: #269
