### ISSUE TITLE
Add elemental damage type options to Ant creation in Ant editor

### ISSUE THREAD

**Issue by anthonyoffire** [cs481-ekh/s23-scuttlers#234]
- [x] given the user creates an ant, when choosing an ant type, then the user will be prompted to choose an ant element type
- [x] patch up the ai button
- [x] see if scrollpane can be moved over, and new font

**Comment by Jackcunningolf** [comment]
the user may now choose an elemental type for the ant. Tried to get a multi select dialog working but no cigar.

{t:300}
